import randerScript from "./randerScript"

const initBlockly = async () => {
    await randerScript("static/blockly/code/blockly_compressed.js")
    await randerScript("static/blockly/code/blocks_compressed.js")
    await randerScript("static/blockly/code/javascript_compressed.js")
    await randerScript("static/blockly/code/en.js")
    await randerScript("static/blockly/src/graph.js")
    await randerScript("static/blockly/src/graph-gen.js")
    await randerScript("static/blockly/src/systemInformation.js")
    await randerScript("static/blockly/src/systemInformation-gen.js")
    await randerScript("static/blockly/src/clearScreen.js")
    await randerScript("static/blockly/src/clearScreen-gen.js")
    await randerScript("static/blockly/src/delay.js")
    await randerScript("static/blockly/src/delay-gen.js")
    await randerScript("static/blockly/src/control.js")
    await randerScript("static/blockly/src/control-gen.js")
    await randerScript("static/blockly/src/general.js")
    await randerScript("static/blockly/src/general-gen.js")
    await randerScript("static/blockly/src/guide.js")
    await randerScript("static/blockly/src/guide-gen.js")
    await randerScript("static/blockly/src/dialog.js")
    await randerScript("static/blockly/src/dialog-gen.js")
    await randerScript("static/blockly/src/action.js")
    await randerScript("static/blockly/src/action-gen.js")
    await randerScript("static/blockly/src/animate.js")
    await randerScript("static/blockly/src/animate-gen.js")
    await randerScript("static/blockly/src/object.js")
    await randerScript("static/blockly/src/object-gen.js")
    await randerScript("static/blockly/src/canvas.js")
    await randerScript("static/blockly/src/canvas-gen.js")
    await randerScript("static/blockly/src/time.js")
    await randerScript("static/blockly/src/time-gen.js")
    await randerScript("static/blockly/src/async.js")
    await randerScript("static/blockly/src/async-gen.js")
    await randerScript("static/blockly/src/dataExport.js")
    await randerScript("static/blockly/src/dataExport-gen.js")
    await randerScript("static/blockly/src/module.js")
    await randerScript("static/blockly/src/module-gen.js")
}

export default initBlockly